/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: alexeyshadrin80 (https://sketchfab.com/alexeyshadrin80)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grid-b9df4bebf73d44caa241680b01943266
Title: Grid
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Case(props) {
    const { nodes, materials } = useGLTF('/models/Grid 3D Model by Alexey Shadrin.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Empty_Mesh_gr1_0.geometry}
                    material={materials.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Empty_Mesh_gr1_0_1.geometry}
                    material={materials.material}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/models/Grid 3D Model by Alexey Shadrin.glb')
